### ISSUE TITLE
TADA_TwoCharacteristicScatterplot legend should not include fraction and/or speciation if they are NA

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/EPATADA#473]
**Is your feature request related to a problem? Please describe.**

The legend for the TADA_TwoCharacteristicScatterplot in Figures.R looks strange for characteristics that do not require a fraction or speciation and are NA. See example from RShiny App: 

![image](https://github.com/USEPA/TADA/assets/46969696/10328c19-1221-4a51-bb50-5fa174ced511)

**Describe the solution you'd like**

Update TADA_TwoCharacteristicScatterplot so the fraction and/or speciation are not included in the legend titles if they are NA. Keep if not NA.

Example (remove these NAs): 
![image](https://github.com/USEPA/TADA/assets/46969696/cfbe0f29-41cd-4c76-a538-53f05558a56b)

**Comment by hillarymarler** [comment]
I ran into this issue when working on the depth profile plots - the way I dealt with it here may work here too.
