### ISSUE TITLE
Create internal function to remove NAs for figure titles and axis labels

### ISSUE THREAD

**Issue by hillarymarler** [USEPA/EPATADA#481]
**Describe the bug**

In many examples for figure labels (titles and axes), there are "NA"s included in the label because of no speciation/fraction/unit for some TADA.ComparableDataIdentifiers. This has been addressed individually in some functions, but a more efficient solution would be to create an internal function which would remove common iterations of "NA" as observed in the comparable data identifiers and titles generated for figures.

**To Reproduce**

This issue has been corrected individually in TADA_DepthProfilePlot and TADA_TwoCharacteristicScatterplot using a stringr::str_remove_all() approach, but may be seen in other figure generating functions.

**Expected behavior**

The internal function will remove common "NA" strings (ex: "(NA", "(NA)", "_NA", etc.). Thought will need to be given on how to handle spaces before or after NAs so title/label spacing is correct.

**Comment by wokenny13** [comment]
Do you have recommendations of a good .R file location for this sort of function? @hillarymarler

**Comment by hillarymarler** [comment]
My inclination would be to put it in "Utilities.R".
