### ISSUE TITLE
TADA.ComparableDataIdentifier is used for legend labels in TADA_TwoCharacteristicScatterplot uses a different column for id_cols

### ISSUE THREAD

**Issue by hillarymarler** [USEPA/EPATADA#485]
**Describe the bug**

TADA.ComparableDataIdentifier is used for the legend labels in TADA_TwoCharacteristicScatterplot even when a different column has been selected for id_cols. This is confusing when comparing the same characteristic between two monitoring locations, for example:

<img width="622" alt="image" src="https://github.com/USEPA/EPATADA/assets/152432687/1d99001e-bb91-463f-9ba7-5c6f104b473f">

**To Reproduce**

```
df <- dplyr::filter(Data_6Tribes_5y_Harmonized, TADA.ComparableDataIdentifier == "TOTAL PHOSPHORUS, MIXED FORMS_UNFILTERED_AS P_UG/L")
#' # Creates a scatterplot including the two specified sites in the same plot:
TADA_TwoCharacteristicScatterplot(df, id_cols = "MonitoringLocationName", groups = c("Upper Red Lake: West", "Upper Red Lake: West-Central"))
```

**Expected behavior**

Labels for the legend should reflect the column selected in id_cols.

Bug fixes should include all the following work:

-   [ ] Create or edit the function/code.

-   [ ] Document all code using line/inline and/or multi-line/block comments
    to describe what is does.

-   [ ] Create or edit tests in tests/testthat folder to help prevent and/or 
    troubleshoot potential future issues.

-   [ ] Create or edit the function documentation. Include working
    examples.

-   [ ] Update or add the new functionality to the appropriate vignette
    (or create new one).

-   [ ] If function/code edits made as part of this issue impact other
    functions in the package or functionality in the shiny app, ensure
    those are updated as well.
    
-   [ ] Run TADA_UpdateAllRefs(), TADA_UpdateExampleData(), styler::style_pkg(),
    devtools::document(), and devtools::check() and address any new notes or 
    issues before creating a pull request.    

-   [ ] Run more robust check for releases: devtools::check(manual = TRUE, 
    remote = TRUE, incoming = TRUE)

**Comment by wokenny13** [comment]
I'm unsure if this is an issue with the example dataset, but when I ran the above code to reproduce the issue, I only get 50 rows of observation due to the argument **TADA.ComparableDataIdentifier == "TOTAL PHOSPHORUS, MIXED FORMS_UNFILTERED_AS P_UG/L"** being set to the unit **UG/L** but when I changed it to **MG/L** I was able to reproduce the results, just in MG/L instead of UG/L.

df <- dplyr::filter(Data_6Tribes_5y_Harmonized, TADA.ComparableDataIdentifier == "TOTAL PHOSPHORUS, MIXED FORMS_UNFILTERED_AS P_UG/L")

versus

df <- dplyr::filter(Data_6Tribes_5y_Harmonized, TADA.ComparableDataIdentifier == "TOTAL PHOSPHORUS, MIXED FORMS_UNFILTERED_AS P_MG/L")

**Comment by hillarymarler** [comment]
Below is an example of a scatterplot I modified for a demo. See (https://usepa.github.io/EPATADA/articles/TADAWaterSciConWorkshopDemo.html) if you want to see how to create the data set used in the example below.

Maybe it would be possible to conditionally remove the 2nd y-axis if the same characteristic is plotted in both traces? But base the scale on both traces?

What do you think of changing the name to TADA_TwoGroupScatterplot? That might be more descriptive if we are making it flexible enough to accommodate different id_cols inputs.

Or is this starting to get so convoluted that it may make sense to create a separate function for comparing different locations rather than different characteristics? We could discuss tomorrow.

`# create two characteristic scatterplot using TADA_TWoCharacteristicScatterplot
twochar_scatter <- TADA_TwoCharacteristicScatterplot(data %>% 
                 dplyr::filter(ActivityStartDate > "2014-12-31",
                               TADA.ComparableDataIdentifier == 
                                "SPECIFIC CONDUCTANCE_TOTAL_NA_US/CM @25C"),
               id_cols = "ATTAINS.assessmentunitname",
               groups = c("San Juan River (Navajo bnd at Hogback to Animas River)", "Animas River (San Juan River to Estes Arroyo)")) %>%
  # remove default plot features that are not applicable for a location comparison
  plotly::layout(yaxis2 = list(overlaying = "y", side = "right", title = "", visible = FALSE),
                 title = TADA_InsertBreaks("SPECIFIC CONDUCTANCE for the San Juan and Animas Rivers Over Time"))

# create two characteristic scatterplot using TADA_TWoCharacteristicScatterplot
twochar_scatter <- TADA_TwoCharacteristicScatterplot(data %>% 
                 dplyr::filter(ActivityStartDate > "2014-12-31",
                               TADA.ComparableDataIdentifier == 
                                "SPECIFIC CONDUCTANCE_TOTAL_NA_US/CM @25C"),
               id_cols = "ATTAINS.assessmentunitname",
               groups = c("San Juan River (Navajo bnd at Hogback to Animas River)", "Animas River (San Juan River to Estes Arroyo)")) %>%
  # remove default plot features that are not applicable for a location comparison
  plotly::layout(yaxis2 = list(overlaying = "y", side = "right", title = "", visible = FALSE),
                 title = TADA_InsertBreaks("SPECIFIC CONDUCTANCE for the San Juan and Animas Rivers Over Time"))`

<img width="560" alt="image" src="https://github.com/USEPA/EPATADA/assets/152432687/8f087ff4-37be-4756-b926-c250b922668e">
