### ISSUE TITLE
Installing EPATADA in RStudio: TADA Module 1

### ISSUE THREAD

**Issue by mariamval** [USEPA/EPATADA#489]
**Does the reference location to install the EPATADA from github changed regarding the one listed in the TADA Module 1?**

Hi everyone, I am a new EPATADA user. I am trying to install the EPATADA library from github in my desktop RStudio following the TADA Module 1 instructions. I am getting the following error:

Code use:
remotes::install_github("USEPA/EPATADA",
                        ref = "471-tada_convertresultunits-is-overwriting-tadamethodspeciationname-with-na",
                        dependencies = TRUE)

Error: Failed to install 'unknown package' from GitHub:
HTTP error 404.
No commit found for the ref 471-tada_convertresultunits-is-overwriting-tadamethodspeciationname-with-na

Does the "ref 471-tada_convertresultunits-is-overwriting-tadamethodspeciationname-with-na" changed? If so, could you please guide me in the appropriate ref to use.

Thank you in advance for your help.

**Comment by wokenny13** [comment]
Hi Maria, try **ref = develop**

remotes::install_github("USEPA/EPATADA",
ref = "develop",
dependencies = TRUE)

**Comment by hillarymarler** [comment]
Vignettes have been updated to reflect "ref = develop".
