### ISSUE TITLE
TADA.ComparableDataIdentifier column showing NA for the TADA.ResultMeasure.MeasureUnitCode portion of its string pasting

### ISSUE THREAD

**Issue by wokenny13** [USEPA/EPATADA#502]
**Describe the bug**

NA units in the TADA.ComparableDataIdentifier may be related to non-detects or TADA_SimpleCensoredMethods.

There are also some fields where the speciation seems to be showing up in the last portion of the pasting string with an NA portion prior, highlighted in orange. Unsure if this is a related issue or an expected output.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/09ae8177-af9d-4956-9aaa-d9d06026ac67">

**To Reproduce**

Code to reproduce the behavior:

``` r
library(EPATADA)

# load example data
data(Data_Nutrients_UT)
# This shows the unique fields for the dataset found in TADA.ComparableDataIdentifier. NA found in the last portion of each field are found for items such as "NITRATE_DISSOLVED_NA_NA", "NITROGEN_SUSPENDED_NA_NA, "NITRATE_TOTAL_AS N_NA" and others.
unique(Data_Nutrients_UT$TADA.ComparableDataIdentifier)
```

**Expected behavior**

TADA.ResultMeasure.MeasureUnitCode should show for fields such as  "NITRATE_TOTAL_AS N_MG/L" rather than  "NITRATE_TOTAL_AS N_NA"

**Comment by hillarymarler** [comment]
Adding comments from TADA Team meeting:

- Check usgs speciation in TADA_ConvertResultUnits to make sure that units/method speciations are being transferred correctly for usgs samples
- Check to make sure that TADA_CreateComparableDataIdentifier is being run each time there are changes to the TADA.ResultMeasure.ResultMeasureUnit and TADA.MethodSpeciation fields in TADA_AutoClean and TADA_ConvertResultUnits
