### ISSUE TITLE
Flag column values are inconsistent (Rejected, Invalid, Suspect vs. Accepted, Valid, Pass)

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/EPATADA#515]
**Is your feature request related to a problem? Please describe:**

Flag function outputs are still inconsistent (three variations of each). It would be more user friendly if they all used the same flag names (e.g., Rejected, Invalid, Suspect vs. Accepted, Valid, Pass).

The following flag columns and their associated functions are relevant to this issue:

- TADA.SampleFraction.Flag
- TADA.MethodSpeciation.Flag
- TADA.ResultUnit.Flag
- TADA.ResultValueAboveUpperThreshold.Flag
- TADA.ResultValueBelowLowerThreshold.Flag
- TADA.AnalyticalMethod.Flag
- TADA.MeasureQualifierCode.Flag

**Describe the solution you'd like:**

 Suggest to use Suspect and Pass for consistency.

**Reminders for TADA contributors addressing this issue:**

New features and/or edits should include all the following work:

-   [ ] Create or edit the function/code.

-   [ ] Document all code using line/inline and/or multi-line/block comments
    to describe what is does.

-   [ ] Create or edit tests in tests/testthat folder to help prevent and/or 
    troubleshoot potential future issues.

-   [ ] Create or edit the function documentation. Include working
    examples.

-   [ ] Update or add the new functionality to the appropriate vignette
    (or create new one).

-   [ ] If function/code edits made as part of this issue impact other
    functions in the package or functionality in the shiny app, ensure
    those are updated as well.
    
-   [ ] Run TADA_UpdateAllRefs(), TADA_UpdateExampleData(), styler::style_pkg(),
    devtools::document(), and devtools::check() and address any new notes or 
    issues before creating a pull request.    

-   [ ] Run more robust check for releases: devtools::check(manual = TRUE, 
    remote = TRUE, incoming = TRUE)

**Comment by wokenny13** [comment]
Is it best to create a function that can addressing consistent flagging of column values? Or make a decision to handle them manually? 

*'Suspect' and 'Pass' for consistency is suggested

@hillarymarler did we ever address the flagging consistency with WY/MT? We might need to notify them of this update to their documentation of the WQP/TADA tool they've been working on once this issue has been addressed?

**Comment by hillarymarler** [comment]
@wokenny13 - we will definitely want to communicate with them as we make updates. Also, with the team that is working on a similar tool for AK.
