### ISSUE TITLE
ft, m, in unit conversions not working

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/EPATADA#517]
**Describe the bug**

TADA_ConvertResultUnits was not converting correctly from m, ft, or in to target of in. Ideally, the target for all of these would be m.  I am not sure where the IN target or conversion factors are coming from. 

I think this is coming from the WQX unit domain, but what I am seeing in WQXweb vs. the domain table (https://cdx.epa.gov/wqx/download/DomainValues/MeasureUnit.CSV)  vs. the TADA WQXunitref are not consistent. Need more time to troubleshoot.

**To Reproduce**

Code to reproduce the behavior:

``` r
test <- TADA_DataRetrieval(
  startDate = "2020-01-01",
  endDate = "null",
  countrycode = "null",
  countycode = "null",
  huc = "null",
  siteid = "null",
  siteType = "null",
  characteristicName = "Depth, bottom",
  characteristicType = "null",
  sampleMedia = "null",
  statecode = "null",
  organization = "null",
  project = "null",
  providers = "null",
  applyautoclean = FALSE
)

test2 <- TADA_CreateUnitRef(test)

test3 <- TADA_ConvertResultUnits(test)
```
**Screenshots**

<img width="573" alt="image" src="https://github.com/user-attachments/assets/5dacc99a-2faf-4b90-8d8f-4a5c16e6f199">
**Additional context**

Bug fixes should include all the following work:

-   [ ] Create or edit the function/code.

-   [ ] Document all code using line/inline and/or multi-line/block comments
    to describe what is does.

-   [ ] Create or edit tests in tests/testthat folder to help prevent and/or 
    troubleshoot potential future issues.

-   [ ] Create or edit the function documentation. Include working
    examples.

-   [ ] Update or add the new functionality to the appropriate vignette
    (or create new one).

-   [ ] If function/code edits made as part of this issue impact other
    functions in the package or functionality in the shiny app, ensure
    those are updated as well.
    
-   [ ] Run TADA_UpdateAllRefs(), TADA_UpdateExampleData(), styler::style_pkg(),
    devtools::document(), and devtools::check() and address any new notes or 
    issues before creating a pull request.    

-   [ ] Run more robust check for releases: devtools::check(manual = TRUE, 
    remote = TRUE, incoming = TRUE)

**Comment by hillarymarler** [comment]
I am wrapping up some unit conversion work related to ref = "wqx". Do you want me to take a look at the length unit conversions too?

**Comment by wokenny13** [comment]
The TADA.WQXUnitConversionFactor are all 0.0254 in the screenshot example that Cristina shared, which doesn't seem right.

I am looking at the WQXUnitRef.csv and it seems like that is where that 0.0254 is coming from? Also, the last changed date was recent at 3/26/2024.

![image](https://github.com/user-attachments/assets/4dd3d72f-bab9-43c8-ad16-469a4aa0e145)

I believe the .0254 should be referencing the conversion of Code = 'm' to Target.Unit = 'in' in the table. 

Should the target.unit be in 'm'? Should this be brought up to WQX/WQP team at all? There doesn't seem to be a 'm' Target.Unit in WQXUnitRef at all, only in 'in'.

**Comment by wokenny13** [comment]
![image](https://github.com/user-attachments/assets/af4bdb87-99ac-4948-9259-38ad9fe59232)

Should these 3 rows in the WQXUnitRef be corrected to the values shown in the last column here?

**Comment by wokenny13** [comment]
> ![image](https://private-user-images.githubusercontent.com/169296783/361852980-af4bdb87-99ac-4948-9259-38ad9fe59232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzA4MjYsIm5iZiI6MTcyNDc3MDUyNiwicGF0aCI6Ii8xNjkyOTY3ODMvMzYxODUyOTgwLWFmNGJkYjg3LTk5YWMtNDk0OC05MjU5LTM4YWQ5ZmU1OTIzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNDU1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmUyYjk4NWM5ZWRkMzM0NDQ2ZTU2ZDQ3NWRiMDc0MWFhYjhmMTcyY2Y1ODM0ODY3Mjc2NmEwNzZmMTY3YmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7vQJShpVupsNB0KAUmnZ4iro4BSuxGzRADR4z7znMZ0)
> 
> Should these 3 rows in the WQXUnitRef be corrected to the values shown in the last column here?

I believe these conversion factors are correct if the Target.Unit for these 3 rows were changed to 'm'
