### ISSUE TITLE
Test failure when TADA_RandomTestingData provides no results

### ISSUE THREAD

**Issue by hillarymarler** [USEPA/EPATADA#556]
There are occasional test failures due to no data returned from a TADA_RandomTestingData query.

An example can be seen here: https://github.com/USEPA/EPATADA/actions/runs/12357853259/job/34487062959?pr=555 (see line 1878).

![image](https://github.com/user-attachments/assets/0cf0a0a8-09d9-49ad-8ea1-a9d4c3f4d2e6)

We've addressed this in a couple of tests that use TADA_RandomTestingData, but there are more places we need to do so such as the test for "TADA_AutoClean function does not grow dataset" in test-Utilities.R.

Could be addressed in each test or update TADA_RandomTestingData to ensure that a data set containing some minimum number of entries is returned.

**Comment by cristinamullin** [comment]
I think it is reasonable to require at least 10 results return with TADA_RandomTestingData

**Comment by hillarymarler** [comment]
10 seems reasonable to me. We may also want to review whether random results from a single state vs. a single state are more appropriate for each test. Allowing a random data set from all states is more likely to yield > 10 results, but results from a single state are more appropriate for some tests (ex: looking for duplicates, continuous data, etc.)
